layout_spectrum: 1
typography_spectrum: 0.3958109
color:
  saturation: 1
  brandStrength: 0.91941
  lightness: 0
  rhythmicContrast: 0.8630504
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
name: Let Go and Have Faith
